# MATH 210 Introduction to Mathematical Computing

## March 9, 2022

* Simpsons's rule
* Implementation
* Error formula

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Simpson's Rule

Simpson's rule is the result of approximating $f(x)$ with degree 2 Taylor polynomials. We assume that $N$ is even. The formula is

$$
\sum_{n=1}^{N/2} \frac{f(x_{2n}) + 4 f(x_{2n-1}) + f(x_{2n-2})}{3} (x_n - x_{n-1})
$$

Write a function called `simpsons` which takes `f`, `a`, `b` and `N` (assume $N$ is even) and returns Simpson's rule approximation.

In [2]:
def simpsons(f,a,b,N):
    x = np.linspace(a,b,N+1)
    y = f(x)
    terms = y[2::2] + 4*y[1::2] + y[:-1:2]
    return np.sum(terms)/3*(b - a)/N

Verify our function on an example where we know the exact answer:

$$
\int_0^{\pi/4} \sin^2(x) \, dx = \frac{\pi}{4}
$$

In [27]:
f = lambda x: np.sin(x)**2
a = 0; b = np.pi/2; N = 4
simpsons(f,a,b,N)

0.7853981633974483

In [28]:
np.pi/4

0.7853981633974483

Note that we select slices of vectors consisting of every second entry by the syntax:

In [5]:
v = np.linspace(0,1,11)
v

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [6]:
v[2::2]

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [7]:
v[1::2]

array([0.1, 0.3, 0.5, 0.7, 0.9])

In [8]:
v[:-1:2]

array([0. , 0.2, 0.4, 0.6, 0.8])

## Error formula

Introduce notation for Simpson's rule on $N$ equal subintervals

$$
S_N(f) = \frac{b-a}{3N} \sum_{n=1}^{N/2} (f(x_{2n}) + 4 f(x_{2n-1}) + f(x_{2n-2}))
$$

A bound on the error is given by

$$
E_N^S(f) = \left| \int_a^b f(x) dx - S_N(f) \right| \leq \frac{(b-a)^5}{180N^4}K_4
$$

where $|f''''(x)| \leq K_4$ for all $x \in [a,b]$.

What can we say about $E_N^S(f)$ if $f(x)$ is a degree 3 polynomial? If $f(x) = c_0 + c_1 x + c_2 x^2 + c_3 x^3$ then $f''''(x) = 0$ therefore $E_N^S(f) = 0$. In other words, Simpson's rule is exact for any degree 3 polynomial and any $N$.

## NumPy and SciPy functions

There are NumPy ans SciPy functions to implement numerical integration.

In [34]:
f = lambda x: np.exp(-x**2)
a = 0; b = 1; N = 10
x = np.linspace(a,b,N+1)
y = f(x)
np.trapz(y,x)

0.7462107961317493

In [35]:
import scipy.integrate as spi

In [36]:
f = lambda x: np.exp(-x**2)
a = 0; b = 1; N = 4
x = np.linspace(a,b,N+1)
y = f(x)
spi.simpson(y,x)

0.7468553797909873