# MATH 210 Introduction to Mathematical Computing

## March 4, 2022

* NumPy indexing and slicing
* Midpoint rule
* Error formula
* Examples

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## NumPy indexing and slicing

Use square bracket syntax to access entries in a NumPy array:

In [2]:
x = np.linspace(0,1,11)
print(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [3]:
x[0]

0.0

In [4]:
x[3]

0.30000000000000004

In [5]:
x[-1]

1.0

Use the colon syntax `x[a:b]` to access a slice of the array from index `a` up to (but not including) `b`:

In [6]:
x[0:4]

array([0. , 0.1, 0.2, 0.3])

In [7]:
x[:4]

array([0. , 0.1, 0.2, 0.3])

In [8]:
x[7:]

array([0.7, 0.8, 0.9, 1. ])

For example, the right endpoints of `x` correspond to:

In [9]:
x[1:]

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Midpoint rule

The midpoint rule is the Riemann in which we choose values $f(x_n^*)$ at the midpoints of the intervals

$$
\int_a^b f(x) dx \approx \sum_{n=1}^N f(x_n^*) (x_n - x_{n-1})
$$

where $x_n^* = (x_n + x_{n-1})/2$.

Write a function called `midpoint` which takes `f`, `a`, `b` and `N` and returns the midpoint Riemann approximation on $N$ subintervals of equal length.

In [10]:
def midpoint(f,a,b,N):
    x = np.linspace(a,b,N+1)
    x_mid = (x[:-1] + x[1:])/2
    return (b - a)/N*np.sum(f(x_mid))

In [11]:
f = lambda x: x**2 - 1
a = 0; b = 1; N = 1;
midpoint(f,a,b,N)

-0.75

In [12]:
f = lambda x: np.sin(x)
a = 0; b = np.pi; N = 1000;
midpoint(f,a,b,N)

2.0000008224672703

## Error formula

Introduce notation for midpoint Riemann sum approximation on $N$ subintervals of equal length

$$
M_N(f) = \frac{b-a}{N} \sum_{n=1}^N f(x_n^*)
$$

where $x_n^* = (x_n + x_{n-1})/2$. The bound on the error is

$$
E_N^M(f) = \left| \int_a^b f(x)dx - M_N(f) \right| \leq \frac{(b-a)^3}{24 N^2}K_2
$$

where $| f''(x) | \leq K_2$ for all $x \in [a,b]$.

## Example

Find $N$ which guarantees the error for the midpoint Riemann sum approximation of

$$
\int_1^2 x^x dx
$$

is less than 0.001. (Recall we found $N=3387$ for right Riemann sum to have less than this error.)  First step is to compute $f'(x)$. Use logarithmic differentiation

$$
y = x^x \Rightarrow \ln(y) = x \ln(x) \Rightarrow \frac{1}{y} y' = \ln(x) + 1
\Rightarrow y' = x^x(\ln(x) + 1)
$$

Now compute $f''(x)$

$$
f''(x) = x^x(\ln(x) + 1)^2 + x^x(1/x)
$$

Note that:

* $x^x$ is increasing on $[1,2]$ therefore $x^x \leq 2^2$
* $\ln(x)$ is increasing on $[1,2]$ therefore $\ln(x) \leq \ln(2)$
* $1/x$ is decreasing on $[1,2]$ therefore $1/x \leq 1$

Put it all together to find:

$$
| f''(x) | \leq 2^2(\ln(2) + 1)^2 + 2^2(1/1)
$$

In [13]:
2**2*(np.log(2) + 1)**2 + 2**2/2

13.46698950015237

In [14]:
E = 0.001; a = 1; b = 2; K2 = 15.46698950015237
N = np.sqrt((b - a)**3/24/E*K2)
N

25.38617528970605

In [15]:
f = lambda x: x**x
a = 1; b = 2; N = 26;
midpoint(f,a,b,N)

2.050090497013929